### ISSUE TITLE
Asio finding Path in Simple-Web-Server's CMakeLists.txt

### ISSUE THREAD

**Issue by JusticeBoi** [stianang/angelsenCppWeb#1]
Hey,

First of all thank you for this repo, I have been thinking about using C++ to develop my cite but was too afraid to start.

Secondly, following the installation guide in readme gave me a few errors about <asio.hpp> header not being found. I figured the problem was from CMakeLists.txt [here](https://github.com/stianang/angelsenCppWeb/blob/master/common/http/Simple-Web-Server/CMakeLists.txt) starting from line 25:

``` cmake
find_file(HAVE_ASIO asio.hpp PATHS /home/stian/EasyWeb/common/http/asio-1.12.2/include)
target_include_directories(simple-web-server
        INTERFACE /home/stian/EasyWeb/common/http/asio-1.12.2/include)
```

 I am very far from an expert in CMake, but may I suggest a change to make these path arguments more general, maybe like  :
``` cmake
find_file(HAVE_ASIO asio.hpp PATHS ${CMAKE_CURRENT_SOURCE_DIR}/../asio-1.12.2/include)
target_include_directories(simple-web-server
        INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/../asio-1.12.2/include)
``` 
After these changes, the build process worked out of the box , without changing anything else.

It might make the building process more robust, but as I said I am just a learner and thought this could be a point of interest for you.

Thanks!

**Comment by stianang** [comment]
You are absolutely right, and I added your fix. Thanks! :)
